/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Checkpoint } from "./domain/models/checkpoint";
import { GetShipmentDetails } from "./domain/usages/get-shipment-details";
import { Shipment } from "./domain/models/shipment";
export namespace Components {
    interface BluedartTrackingComponent {
        /**
          * The checkpoints
         */
        "checkpoints": boolean;
        /**
          * The tracking number
         */
        "trackingNumber": string;
    }
    interface LoadingComponent {
    }
    interface NoDataComponent {
    }
    interface ShipmentCheckpointsComponent {
        /**
          * The shipment checkpoints.
         */
        "checkpoints": Checkpoint[];
    }
    interface ShipmentComponent {
        /**
          * The checkpoints
         */
        "checkpoints": boolean;
        /**
          * Get Shipment details
         */
        "getShipmentDetails": GetShipmentDetails;
        /**
          * The tracking number
         */
        "trackingNumber": string;
    }
    interface ShipmentDetailsFactory {
        "checkpoints": boolean;
        "trackingNumber": string;
    }
    interface ShipmentMetaComponent {
        /**
          * The shipment details
         */
        "data": Shipment;
    }
}
declare global {
    interface HTMLBluedartTrackingComponentElement extends Components.BluedartTrackingComponent, HTMLStencilElement {
    }
    var HTMLBluedartTrackingComponentElement: {
        prototype: HTMLBluedartTrackingComponentElement;
        new (): HTMLBluedartTrackingComponentElement;
    };
    interface HTMLLoadingComponentElement extends Components.LoadingComponent, HTMLStencilElement {
    }
    var HTMLLoadingComponentElement: {
        prototype: HTMLLoadingComponentElement;
        new (): HTMLLoadingComponentElement;
    };
    interface HTMLNoDataComponentElement extends Components.NoDataComponent, HTMLStencilElement {
    }
    var HTMLNoDataComponentElement: {
        prototype: HTMLNoDataComponentElement;
        new (): HTMLNoDataComponentElement;
    };
    interface HTMLShipmentCheckpointsComponentElement extends Components.ShipmentCheckpointsComponent, HTMLStencilElement {
    }
    var HTMLShipmentCheckpointsComponentElement: {
        prototype: HTMLShipmentCheckpointsComponentElement;
        new (): HTMLShipmentCheckpointsComponentElement;
    };
    interface HTMLShipmentComponentElement extends Components.ShipmentComponent, HTMLStencilElement {
    }
    var HTMLShipmentComponentElement: {
        prototype: HTMLShipmentComponentElement;
        new (): HTMLShipmentComponentElement;
    };
    interface HTMLShipmentDetailsFactoryElement extends Components.ShipmentDetailsFactory, HTMLStencilElement {
    }
    var HTMLShipmentDetailsFactoryElement: {
        prototype: HTMLShipmentDetailsFactoryElement;
        new (): HTMLShipmentDetailsFactoryElement;
    };
    interface HTMLShipmentMetaComponentElement extends Components.ShipmentMetaComponent, HTMLStencilElement {
    }
    var HTMLShipmentMetaComponentElement: {
        prototype: HTMLShipmentMetaComponentElement;
        new (): HTMLShipmentMetaComponentElement;
    };
    interface HTMLElementTagNameMap {
        "bluedart-tracking-component": HTMLBluedartTrackingComponentElement;
        "loading-component": HTMLLoadingComponentElement;
        "no-data-component": HTMLNoDataComponentElement;
        "shipment-checkpoints-component": HTMLShipmentCheckpointsComponentElement;
        "shipment-component": HTMLShipmentComponentElement;
        "shipment-details-factory": HTMLShipmentDetailsFactoryElement;
        "shipment-meta-component": HTMLShipmentMetaComponentElement;
    }
}
declare namespace LocalJSX {
    interface BluedartTrackingComponent {
        /**
          * The checkpoints
         */
        "checkpoints"?: boolean;
        /**
          * The tracking number
         */
        "trackingNumber"?: string;
    }
    interface LoadingComponent {
    }
    interface NoDataComponent {
    }
    interface ShipmentCheckpointsComponent {
        /**
          * The shipment checkpoints.
         */
        "checkpoints"?: Checkpoint[];
    }
    interface ShipmentComponent {
        /**
          * The checkpoints
         */
        "checkpoints"?: boolean;
        /**
          * Get Shipment details
         */
        "getShipmentDetails"?: GetShipmentDetails;
        /**
          * The tracking number
         */
        "trackingNumber"?: string;
    }
    interface ShipmentDetailsFactory {
        "checkpoints"?: boolean;
        "trackingNumber"?: string;
    }
    interface ShipmentMetaComponent {
        /**
          * The shipment details
         */
        "data"?: Shipment;
    }
    interface IntrinsicElements {
        "bluedart-tracking-component": BluedartTrackingComponent;
        "loading-component": LoadingComponent;
        "no-data-component": NoDataComponent;
        "shipment-checkpoints-component": ShipmentCheckpointsComponent;
        "shipment-component": ShipmentComponent;
        "shipment-details-factory": ShipmentDetailsFactory;
        "shipment-meta-component": ShipmentMetaComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bluedart-tracking-component": LocalJSX.BluedartTrackingComponent & JSXBase.HTMLAttributes<HTMLBluedartTrackingComponentElement>;
            "loading-component": LocalJSX.LoadingComponent & JSXBase.HTMLAttributes<HTMLLoadingComponentElement>;
            "no-data-component": LocalJSX.NoDataComponent & JSXBase.HTMLAttributes<HTMLNoDataComponentElement>;
            "shipment-checkpoints-component": LocalJSX.ShipmentCheckpointsComponent & JSXBase.HTMLAttributes<HTMLShipmentCheckpointsComponentElement>;
            "shipment-component": LocalJSX.ShipmentComponent & JSXBase.HTMLAttributes<HTMLShipmentComponentElement>;
            "shipment-details-factory": LocalJSX.ShipmentDetailsFactory & JSXBase.HTMLAttributes<HTMLShipmentDetailsFactoryElement>;
            "shipment-meta-component": LocalJSX.ShipmentMetaComponent & JSXBase.HTMLAttributes<HTMLShipmentMetaComponentElement>;
        }
    }
}
